baseurl = "https://stevehemingway.github.io/"
languageCode = "en-gb"
title = "Steve Hemingway"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "stevehem"

[params]
	subtitle = "The blog of a geek manqué"
	[params.author]
		name = "Steve"
		avatar = "/images/avatar.jpg"
		bio = "Chemist, physicist, programmer, quant, family man"
		github = "stevehemingway/stevehemingway.github.io"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
