baseURL = ""
languageCode = "en-gb"
title = "Steve's Blog"
theme = "bare"
enableGitInfo = false
disableAttribution=true 

publishDir = "docs"

[taxonomies]
  tag = "tags"
#  series = "series"

[params]
mainSections = ["post"]
author = "Steve Hemingway"
email = "steve@stevehemingway.com"
# repoLink = "https://github.com/orf/bare-hugo-theme"
description = 'Community Blogger from Knebworth'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = false
disableAttribution = true

[[params.social]]
icon = "github"
# url = "https://github.com/orf/"
