baseurl = "https://stevehemingway.github.io/"
publishDir= "public"
languageCode = "en"
title = "Steve's Blog"
theme = "hemingway2"
copyright = "theme &copy; <a href=\"https://github.com/beli3ver\">Malte Kiefer</a> 2016"
disqusShortname = "stevehem"
googleAnalytics = ""

description = "Yet another random blog"
keywords = ["software", "politics"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/stevehemingway"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/stevehemingway"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/stevehem"
fa_icon = "fa-twitter"

#[[params.social]]
# url = "https://telegram.me/beli3ver"
# fa_icon = "fa-telegram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
